# 2

In [1]:
import numpy as np
import numpy.linalg as la
import matplotlib.pyplot as pt

In [2]:
u = [[1,0,0,0],[0,0,0,1],[0,0,1,0],[0,1,0,0]]
u_1 = [[1,0],[0,0],[0,0],[0,1]]

In [3]:
s = [[4,0,0,0],[0,3,0,0],[0,0,2,0],[0,0,0,1]]
s_1 = [[4,0],[0,3]]

In [4]:
v = [[1,0,0,0,0],[0,1,0,0,0],[0,0,1,0,0],[0,0,0,1,0]]
v_1 = [[1,0,0,0,0],[0,1,0,0,0]]

In [5]:
#t = np.dot(u_1,s_1)
M = np.dot(np.dot(u_1,s_1), v_1)
M

array([[4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0]])

# 3(a)

In [6]:
X = [[1,2,3],[4,5,6]]

In [7]:
U, sigma, VT = la.svd(X, full_matrices=0)

In [8]:
U[0]

array([-0.3863177 , -0.92236578])

In [9]:
sigma[0]

9.508032000695723

In [10]:
VT

array([[-0.42866713, -0.56630692, -0.7039467 ],
       [ 0.80596391,  0.11238241, -0.58119908]])

In [11]:
U_1 = U[0]
U_1 = U_1.reshape(2,1)

In [12]:
sigma_1 = sigma[0]
sigma_1 = sigma_1.reshape(1,1)

In [13]:
VT_1 = VT[0,:]
VT_1 = VT_1.reshape(1,3)

In [14]:
temp = np.dot(U_1,sigma_1)
temp = temp.reshape(2,1)

In [15]:
M_ = np.dot(temp, VT_1)
M_

array([[1.57454629, 2.08011388, 2.58568148],
       [3.75936076, 4.96644562, 6.17353048]])